### ISSUE TITLE
Miss detection on lowercase useragents.

### ISSUE THREAD

**Issue by blackheart01** [mileusna/useragent#18]
I've noticed that if you force a user agent to lowercase, the parser is no longer able to properly detect the browser. I'm not sure if this is because case sensitivity is required to properly parse a user agent, or if its an over site/bug. I can easily work around this by not forcing to lowercase before parsing, but figured I should let you know of the issue.

**Comment by mileusna** [comment]
I will try in tests, but User Agent strings are exact strings and AppleWebKit/537.36 will always be AppleWebKit and not applewebkit etc. so I don't see the need to support lowercase user agent strings.
Unless there is some very reasonable explanation why it should be done, I will not change the code for this since something might break in the process and I don't believe it is worth the risk.

**Comment by blackheart01** [comment]
That sounds reasonable to me. My use case is certainly not a compelling reason to change the code, as I can easily work around the situation. Its my code that's forcing user agents to lowercase prior to parsing, so I'll just hold off on that until post parsing.
